# DH PARAMETER RECOMMENDATION

# 03
# Note: Average Result from 20180805 test group. The data sets was taken twice at the same Polaris 0 deg configuration. The base frame z is rotated about its y for about 70 degs.

# ---
# DH_0 TO DH_1 FRAME
theta_1: 3.141593 
alpha_1: -1.5654545
a_1: 0.0053875
d_1: 0.000000 

# DH_1 TO DH_2 FRAME
theta_2: -1.569949
alpha_2: 1.563795
a_2: 0.0002515
d_2: -0.0018725

# DH_2 TO DH_3 FRAME
d_3: -0.0080085
j3_scale_factor: 0.9882935
# ---
